name: dev

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      APP_NAME: repofi
      SKIP_ENV_VALIDATION: 1
      NEXT_PUBLIC_SITE_URL: https://alpha-launch.repofi.io/
      NEXT_PUBLIC_CHAIN_ID: 11155111
      NEXT_PUBLIC_REOWN_PROJECT_ID: d198cf7bba856bb5f9a7ec73cb03235e
      NEXT_PUBLIC_CONTRACT_SWAP_ROUTER_ADDRESS: '0x3bFA4769FB09eefC5a80d6E87c3B9C650f7Ae48E'
      NEXT_PUBLIC_CONTRACT_QUOTER_ADDRESS: '0xEd1f6473345F45b75F8179591dd5bA1888cf2FB3'
      NEXT_PUBLIC_CONTRACT_V3_FACTORY_ADDRESS: '0x0227628f3F023bb0B980b67D528571c95c6DaC1c'
      NEXT_PUBLIC_GIT_SHA: ${{ github.sha }}
    steps:
      - name: "Get branch name and save to env"
        env:
          IS_PR: ${{ github.EVENT_NAME == 'pull_request' }}
        run: |
          if ${IS_PR}; then
            TAG="${GITHUB_HEAD_REF}"
          else
            TAG="${GITHUB_REF##*/}"
          fi
          echo "TAG=${TAG}" >> $GITHUB_ENV

      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          version: 9.14.2

      - uses: actions/setup-node@v4
        with:
          node-version: 22.10.0
          cache: "pnpm"
          cache-dependency-path: pnpm-lock.yaml
          registry-url: https://npm.pkg.github.com

      - name: Install dependencies
        run: pnpm install

      - name: Build
        run: pnpm build

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: swr.ap-southeast-3.myhuaweicloud.com
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Publish to Docker Repository
        uses: elgohr/Publish-Docker-Github-Action@v5
        with:
          registry: swr.ap-southeast-3.myhuaweicloud.com
          name: scantist-images/${{ env.APP_NAME }}:${{ env.TAG }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
    outputs:
      tag: ${{ env.TAG }}
      app_name: ${{ env.APP_NAME }}

  update:
    runs-on: ubuntu-latest
    env:
      GKE_CLUSTER_NAME: v4-staging-gke
      GKE_CLUSTER_ZONE: asia-southeast1-b
      GKE_PROJECT_ID: scantist-v4-staging
      GKE_CLUSTER_NAMESPACE: repofi
    needs: build
    steps:
      - id: 'auth'
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.CREDENTIALS_JSON }}'

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v2'
        with:
          version: '>= 513.0.0'
      - name: 'Use gcloud CLI'
        run: 'gcloud info'
      - id: 'get-credentials'
        uses: 'google-github-actions/get-gke-credentials@v2'
        with:
          cluster_name: ${{ env.GKE_CLUSTER_NAME }}
          location: ${{ env.GKE_CLUSTER_ZONE }}
      - id: 'get-pods'
        run: 'kubectl get pods'
